nf_core_version: 3.1.2
repository_type: pipeline
template:
  author: Bozena Mika-Gospodorz and Regan Hayward
  description: Dual RNA-seq pipeline
  force: false
  is_nfcore: true
  name: dualrnaseq
  org: nf-core
  outdir: .
  version: 2.0dev
